// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAszXzqXeBB0I9oID0tff7Gm7DVrsadUhI',
    appId: '1:1052463588677:web:3c04777cd5c4e50fe48a2c',
    messagingSenderId: '1052463588677',
    projectId: 'login-6ccad',
    authDomain: 'login-6ccad.firebaseapp.com',
    storageBucket: 'login-6ccad.appspot.com',
    measurementId: 'G-F0051WENN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQQ5i3XOCu_zx2qlvC2JMSMq8LHNMTpzg',
    appId: '1:1052463588677:android:f4a4ddacaa2f84dde48a2c',
    messagingSenderId: '1052463588677',
    projectId: 'login-6ccad',
    storageBucket: 'login-6ccad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0sDPqn-sLIM9-x52ivalmrzrc2ReYexs',
    appId: '1:1052463588677:ios:7b603c54482279a4e48a2c',
    messagingSenderId: '1052463588677',
    projectId: 'login-6ccad',
    storageBucket: 'login-6ccad.appspot.com',
    iosBundleId: 'com.example.week11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0sDPqn-sLIM9-x52ivalmrzrc2ReYexs',
    appId: '1:1052463588677:ios:585b410ddf4b1176e48a2c',
    messagingSenderId: '1052463588677',
    projectId: 'login-6ccad',
    storageBucket: 'login-6ccad.appspot.com',
    iosBundleId: 'com.example.week11.RunnerTests',
  );
}
